/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/charts/Bar.vue')['default']
    CompareView: typeof import('./components/CompareView.vue')['default']
    DataView: typeof import('./components/DataView.vue')['default']
    DetailView: typeof import('./components/DetailView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./components/Header.vue')['default']
    Horizon: typeof import('./components/charts/Horizon.vue')['default']
    IAntDesignCaretDownFilled: typeof import('~icons/ant-design/caret-down-filled')['default']
    IAntDesignCaretUpFilled: typeof import('~icons/ant-design/caret-up-filled')['default']
    IAntDesignClearOutlined: typeof import('~icons/ant-design/clear-outlined')['default']
    IAntDesignCloseCircleOutlined: typeof import('~icons/ant-design/close-circle-outlined')['default']
    IAntDesignUndoOutlined: typeof import('~icons/ant-design/undo-outlined')['default']
    IAntDesignZoomInOutlined: typeof import('~icons/ant-design/zoom-in-outlined')['default']
    IAntDesignZoomOutOutlined: typeof import('~icons/ant-design/zoom-out-outlined')['default']
    IMdiSelectDrag: typeof import('~icons/mdi/select-drag')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    Radar: typeof import('./components/charts/Radar.vue')['default']
    Root: typeof import('./components/charts/Root.vue')['default']
    SankeyTree: typeof import('./components/charts/SankeyTree.vue')['default']
    TimeSeries: typeof import('./components/charts/TimeSeries.vue')['default']
    TreeView: typeof import('./components/TreeView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
